FROM node:10
#Create app directory
WORKDIR /usr/src/app
#Copy over JSON files
COPY package*.json ./
#Install dependencies
RUN npm install
#Copy the app source code to the image
COPY . .
#Expose the port
EXPOSE 300
#Run the server
CMD ["node", "app.js"]

